# Generated by Django 2.2.5 on 2020-02-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0002_remove_main_lastaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='HighScore',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Status',
            new_name='hs',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='passhash',
            new_name='sts',
        ),
    ]
