# Generated by Django 2.2.5 on 2020-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0004_auto_20200220_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264, unique=True)),
                ('icon', models.CharField(max_length=264)),
            ],
        ),
    ]
